apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/ncloud-load-balancer-layer-type: nplb
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer